# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/aleksejs/work/git/codes/file-formats/HHNE/nwbgui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1507, 1266)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTabWidget.setEnabled(True)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.overviewTab)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.overviewLayout = QtWidgets.QGridLayout()
        self.overviewLayout.setContentsMargins(11, 11, 11, 11)
        self.overviewLayout.setSpacing(6)
        self.overviewLayout.setObjectName("overviewLayout")
        self.overviewTitleLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewTitleLabel.setObjectName("overviewTitleLabel")
        self.overviewLayout.addWidget(self.overviewTitleLabel, 2, 0, 1, 1)
        self.overviewExperimenterLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewExperimenterLabel.setObjectName("overviewExperimenterLabel")
        self.overviewLayout.addWidget(self.overviewExperimenterLabel, 5, 0, 1, 1)
        self.overviewExperimentDescriptionLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewExperimentDescriptionLabel.setObjectName("overviewExperimentDescriptionLabel")
        self.overviewLayout.addWidget(self.overviewExperimentDescriptionLabel, 8, 0, 1, 1)
        self.overviewLabLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewLabLabel.setObjectName("overviewLabLabel")
        self.overviewLayout.addWidget(self.overviewLabLabel, 6, 0, 1, 1)
        self.overviewIdentifierLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewIdentifierLabel.setObjectName("overviewIdentifierLabel")
        self.overviewLayout.addWidget(self.overviewIdentifierLabel, 4, 0, 1, 1)
        self.overviewSessionIDLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewSessionIDLabel.setObjectName("overviewSessionIDLabel")
        self.overviewLayout.addWidget(self.overviewSessionIDLabel, 9, 0, 1, 1)
        self.overviewSessionDescriptionLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewSessionDescriptionLabel.setObjectName("overviewSessionDescriptionLabel")
        self.overviewLayout.addWidget(self.overviewSessionDescriptionLabel, 3, 0, 1, 1)
        self.overviewSessionDescriptionLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewSessionDescriptionLineEdit.setObjectName("overviewSessionDescriptionLineEdit")
        self.overviewLayout.addWidget(self.overviewSessionDescriptionLineEdit, 3, 1, 1, 1)
        self.overviewSessionTimeLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewSessionTimeLabel.setObjectName("overviewSessionTimeLabel")
        self.overviewLayout.addWidget(self.overviewSessionTimeLabel, 10, 0, 1, 1)
        self.overviewSessionTimeNowButton = QtWidgets.QPushButton(self.overviewTab)
        self.overviewSessionTimeNowButton.setObjectName("overviewSessionTimeNowButton")
        self.overviewLayout.addWidget(self.overviewSessionTimeNowButton, 10, 2, 1, 1)
        self.overviewSessionTimeLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewSessionTimeLineEdit.setObjectName("overviewSessionTimeLineEdit")
        self.overviewLayout.addWidget(self.overviewSessionTimeLineEdit, 10, 1, 1, 1)
        self.overviewFileLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewFileLabel.setObjectName("overviewFileLabel")
        self.overviewLayout.addWidget(self.overviewFileLabel, 1, 0, 1, 1)
        self.overviewFileLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewFileLineEdit.setEnabled(True)
        self.overviewFileLineEdit.setReadOnly(True)
        self.overviewFileLineEdit.setObjectName("overviewFileLineEdit")
        self.overviewLayout.addWidget(self.overviewFileLineEdit, 1, 1, 1, 1)
        self.overviewTitleLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewTitleLineEdit.setObjectName("overviewTitleLineEdit")
        self.overviewLayout.addWidget(self.overviewTitleLineEdit, 2, 1, 1, 1)
        self.overviewInstitutionLabel = QtWidgets.QLabel(self.overviewTab)
        self.overviewInstitutionLabel.setObjectName("overviewInstitutionLabel")
        self.overviewLayout.addWidget(self.overviewInstitutionLabel, 7, 0, 1, 1)
        self.overviewIdentifierLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewIdentifierLineEdit.setObjectName("overviewIdentifierLineEdit")
        self.overviewLayout.addWidget(self.overviewIdentifierLineEdit, 4, 1, 1, 1)
        self.overviewExperimenterLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewExperimenterLineEdit.setObjectName("overviewExperimenterLineEdit")
        self.overviewLayout.addWidget(self.overviewExperimenterLineEdit, 5, 1, 1, 1)
        self.overviewLabLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewLabLineEdit.setObjectName("overviewLabLineEdit")
        self.overviewLayout.addWidget(self.overviewLabLineEdit, 6, 1, 1, 1)
        self.overviewInstitutionLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewInstitutionLineEdit.setObjectName("overviewInstitutionLineEdit")
        self.overviewLayout.addWidget(self.overviewInstitutionLineEdit, 7, 1, 1, 1)
        self.overviewExperimentDescriptionLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewExperimentDescriptionLineEdit.setObjectName("overviewExperimentDescriptionLineEdit")
        self.overviewLayout.addWidget(self.overviewExperimentDescriptionLineEdit, 8, 1, 1, 1)
        self.overviewSessionIDLineEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.overviewSessionIDLineEdit.setObjectName("overviewSessionIDLineEdit")
        self.overviewLayout.addWidget(self.overviewSessionIDLineEdit, 9, 1, 1, 1)
        self.gridLayout_3.addLayout(self.overviewLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.overviewTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setEnabled(False)
        self.dataTab.setObjectName("dataTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataTab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setContentsMargins(11, 11, 11, 11)
        self.dataLayout.setSpacing(6)
        self.dataLayout.setObjectName("dataLayout")
        self.dataStageComboBox = QtWidgets.QComboBox(self.dataTab)
        self.dataStageComboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.dataStageComboBox.setObjectName("dataStageComboBox")
        self.dataStageComboBox.addItem("")
        self.dataStageComboBox.addItem("")
        self.dataStageComboBox.addItem("")
        self.dataStageComboBox.addItem("")
        self.dataStageComboBox.addItem("")
        self.dataStageComboBox.addItem("")
        self.dataLayout.addWidget(self.dataStageComboBox)
        self.dataTypeComboBox = QtWidgets.QComboBox(self.dataTab)
        self.dataTypeComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.dataTypeComboBox.setObjectName("dataTypeComboBox")
        self.dataTypeComboBox.addItem("")
        self.dataTypeComboBox.addItem("")
        self.dataTypeComboBox.addItem("")
        self.dataTypeComboBox.addItem("")
        self.dataLayout.addWidget(self.dataTypeComboBox)
        self.dataApplyButton = QtWidgets.QPushButton(self.dataTab)
        self.dataApplyButton.setObjectName("dataApplyButton")
        self.dataLayout.addWidget(self.dataApplyButton)
        self.dataImportButton = QtWidgets.QPushButton(self.dataTab)
        self.dataImportButton.setObjectName("dataImportButton")
        self.dataLayout.addWidget(self.dataImportButton)
        self.dataGuessParamButton = QtWidgets.QPushButton(self.dataTab)
        self.dataGuessParamButton.setEnabled(False)
        self.dataGuessParamButton.setObjectName("dataGuessParamButton")
        self.dataLayout.addWidget(self.dataGuessParamButton)
        self.dataExtraFieldButton = QtWidgets.QPushButton(self.dataTab)
        self.dataExtraFieldButton.setEnabled(False)
        self.dataExtraFieldButton.setObjectName("dataExtraFieldButton")
        self.dataLayout.addWidget(self.dataExtraFieldButton)
        self.dataClearButton = QtWidgets.QPushButton(self.dataTab)
        self.dataClearButton.setEnabled(False)
        self.dataClearButton.setObjectName("dataClearButton")
        self.dataLayout.addWidget(self.dataClearButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dataLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.dataLayout)
        self.dataFeaturesTreeWidget = QtWidgets.QTreeWidget(self.dataTab)
        self.dataFeaturesTreeWidget.setObjectName("dataFeaturesTreeWidget")
        self.dataFeaturesTreeWidget.header().setMinimumSectionSize(200)
        self.verticalLayout.addWidget(self.dataFeaturesTreeWidget)
        self.dataMetaTreeWidget = QtWidgets.QTreeWidget(self.dataTab)
        self.dataMetaTreeWidget.setEnabled(False)
        self.dataMetaTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dataMetaTreeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dataMetaTreeWidget.setObjectName("dataMetaTreeWidget")
        self.dataMetaTreeWidget.header().setDefaultSectionSize(200)
        self.dataMetaTreeWidget.header().setMinimumSectionSize(200)
        self.verticalLayout.addWidget(self.dataMetaTreeWidget)
        self.mainTabWidget.addTab(self.dataTab, "")
        self.gridLayout.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        self.pyOutTextEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.pyOutTextEdit.setMinimumSize(QtCore.QSize(0, 300))
        self.pyOutTextEdit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.pyOutTextEdit.setObjectName("pyOutTextEdit")
        self.gridLayout.addWidget(self.pyOutTextEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1507, 29))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoadParamFile = QtWidgets.QAction(MainWindow)
        self.actionLoadParamFile.setObjectName("actionLoadParamFile")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionLoadParamFile)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInfo)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Happy HIFO NWB Editor"))
        self.overviewTitleLabel.setText(_translate("MainWindow", "Title"))
        self.overviewExperimenterLabel.setText(_translate("MainWindow", "Experimenter"))
        self.overviewExperimentDescriptionLabel.setText(_translate("MainWindow", "Experiment desctiption"))
        self.overviewLabLabel.setText(_translate("MainWindow", "Lab"))
        self.overviewIdentifierLabel.setText(_translate("MainWindow", "Identifier"))
        self.overviewSessionIDLabel.setText(_translate("MainWindow", "Sessoon ID"))
        self.overviewSessionDescriptionLabel.setText(_translate("MainWindow", "Session Description"))
        self.overviewSessionTimeLabel.setText(_translate("MainWindow", "Session Start Time"))
        self.overviewSessionTimeNowButton.setText(_translate("MainWindow", "Now"))
        self.overviewFileLabel.setText(_translate("MainWindow", "Current File"))
        self.overviewInstitutionLabel.setText(_translate("MainWindow", "Institution"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.overviewTab), _translate("MainWindow", "Overview"))
        self.dataStageComboBox.setItemText(0, _translate("MainWindow", "<Select Stage>"))
        self.dataStageComboBox.setItemText(1, _translate("MainWindow", "Acquisition"))
        self.dataStageComboBox.setItemText(2, _translate("MainWindow", "Stimulus"))
        self.dataStageComboBox.setItemText(3, _translate("MainWindow", "Epochs"))
        self.dataStageComboBox.setItemText(4, _translate("MainWindow", "Process"))
        self.dataStageComboBox.setItemText(5, _translate("MainWindow", "Analysis"))
        self.dataTypeComboBox.setItemText(0, _translate("MainWindow", "<Select Type>"))
        self.dataTypeComboBox.setItemText(1, _translate("MainWindow", "Single Photon"))
        self.dataTypeComboBox.setItemText(2, _translate("MainWindow", "Two Photon"))
        self.dataTypeComboBox.setItemText(3, _translate("MainWindow", "EPhys"))
        self.dataApplyButton.setText(_translate("MainWindow", "Apply"))
        self.dataImportButton.setText(_translate("MainWindow", "Import Data"))
        self.dataGuessParamButton.setText(_translate("MainWindow", "Guess parameters"))
        self.dataExtraFieldButton.setText(_translate("MainWindow", "Extra field"))
        self.dataClearButton.setText(_translate("MainWindow", "Clear"))
        self.dataFeaturesTreeWidget.headerItem().setText(0, _translate("MainWindow", "Type"))
        self.dataFeaturesTreeWidget.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.dataMetaTreeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.dataMetaTreeWidget.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.dataTab), _translate("MainWindow", "Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionInfo.setText(_translate("MainWindow", "File Info"))
        self.actionInfo.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionLoadParamFile.setText(_translate("MainWindow", "Load param file..."))
        self.actionLoadParamFile.setShortcut(_translate("MainWindow", "Ctrl+P"))

